# Header
menu:
  home:
    text: Home
    url: /
  services:
    text: Services
    url: services/
  contact:
    text: Contact
    url: contact/
  training:
    text: Training
    url: training/
  products:
    text: Products
    url: products/
    video_p: 
      text: Video-Player
      url: video_p/
    abloop:
      text: Abloop
      url: abloop/
    samaya_app:
      text: Samaya App
      url: samaya_app/
  blog: 
    text: Blog
    url: blog/
  github:
    text: Github
    url: https://github.com/cksachdev
    target : _blank  
  twitter:
    text: Twitter
    url: https://twitter.com/cksachdev
  about:
    text: About me
    url: about/
    team: 
      text: Meet The Team
      url: team/
    about_p:
      text: About Plantyouridea
      url: about_p/
  

# Your avatar url
avatar: /img/cksachdev.jpg
# avatar link
avatar_link: /

# favicon
favicon: /img/favicon.ico

# website
website: Plantyouridea
# website link
website_link: plantyouridea.com
# email
email: mail@chetansachdev.com

# copyright start year
since_year: 2018

# atricle truncation
excerpt_render: true
excerpt_length: 150
excerpt_link: Read more...
mathjax: true
archive_yearly: true